apiVersion: v1
kind: Service
metadata:
  name: retailflow-api
  namespace: dev
  labels:
    app: retailflow-api
spec:
  selector:
    app: retailflow-api
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP